# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test Build and Deploy React App to S3 as static web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v3.1.3
      with:
          name: react-app
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2.1.1
        with:
          name: react-app
          path: ./dist
      - name: Deploy to s3
        uses: reggionick/s3-deploy@v4
        with:
          folder: dist
          bucket: ${{ vars.AWS_S3_BUCKET_NAME }}
          bucket-region: ${{ vars.AWS_REGION }}
